# Site settings
title: Wise Anser
email: mail@wiseanser.com
description: 	"Forget the structure and getting things done."
baseurl: "/"
url: "http://wiseanser.com"
twitter_username: wiseanser
github_username:  efelcie

# Build settings
markdown: kramdown
permalink: pretty
